# Use docker-based build environment (instead of openvz)
sudo: false

language: java
jdk:
  - oraclejdk7

cache:
  directories:
      - '$HOME/.m2/repository'
		
install: /bin/true
script:
  - mvn -B -DTRAVIS_JOB_ID=$TRAVIS_JOB_ID -P COBERTURA clean cobertura:check && mvn -B clean install -Dcobertura.skip=true
